import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { DatabaseSchema, User, UserRole, UserPermissions } from './types.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const DATA_DIR = path.resolve(__dirname, '../data');
const DB_FILE = path.join(DATA_DIR, 'database.json');

export const defaultPermissionsByRole: Record<UserRole, UserPermissions> = {
  super_admin: {
    projects: { view: true, create: true, edit: true, delete: true },
    employees: { view: true, create: true, edit: true, delete: true },
    finance: { view: true, create: true, edit: true, delete: true },
    tasks: { view: true, create: true, edit: true, delete: true },
    clients: { view: true, create: true, edit: true, delete: true },
    reports: { view: true, export: true },
    settings: { view: true, edit: true },
    canViewSalaries: true,
    canViewFinancials: true,
    projectScope: 'all',
  },
  management: {
    projects: { view: true, create: true, edit: true, delete: false },
    employees: { view: true, create: false, edit: false, delete: false },
    finance: { view: true, create: false, edit: false, delete: false },
    tasks: { view: true, create: true, edit: true, delete: false },
    clients: { view: true, create: true, edit: true, delete: false },
    reports: { view: true, export: true },
    settings: { view: true, edit: false },
    canViewSalaries: false,
    canViewFinancials: true,
    projectScope: 'all',
  },
  finance: {
    projects: { view: true, create: false, edit: false, delete: false },
    employees: { view: true, create: false, edit: false, delete: false },
    finance: { view: true, create: true, edit: true, delete: true },
    tasks: { view: true, create: false, edit: false, delete: false },
    clients: { view: true, create: true, edit: true, delete: false },
    reports: { view: true, export: true },
    settings: { view: false, edit: false },
    canViewSalaries: true,
    canViewFinancials: true,
    projectScope: 'all',
  },
  hr: {
    projects: { view: true, create: false, edit: false, delete: false },
    employees: { view: true, create: true, edit: true, delete: true },
    finance: { view: false, create: false, edit: false, delete: false },
    tasks: { view: true, create: false, edit: false, delete: false },
    clients: { view: false, create: false, edit: false, delete: false },
    reports: { view: false, export: false },
    settings: { view: false, edit: false },
    canViewSalaries: true,
    canViewFinancials: false,
    projectScope: 'all',
  },
  project_manager: {
    projects: { view: true, create: true, edit: true, delete: false },
    employees: { view: true, create: false, edit: false, delete: false },
    finance: { view: false, create: false, edit: false, delete: false }, // Only when explicitly granted
    tasks: { view: true, create: true, edit: true, delete: true },
    clients: { view: true, create: true, edit: true, delete: false },
    reports: { view: false, export: false },
    settings: { view: false, edit: false },
    canViewSalaries: false,
    canViewFinancials: false, // Default false for PM per specification
    projectScope: 'assigned_only',
  },
  team_member: {
    projects: { view: true, create: false, edit: false, delete: false },
    employees: { view: true, create: false, edit: false, delete: false },
    finance: { view: false, create: false, edit: false, delete: false },
    tasks: { view: true, create: true, edit: true, delete: false },
    clients: { view: false, create: false, edit: false, delete: false },
    reports: { view: false, export: false },
    settings: { view: false, edit: false },
    canViewSalaries: false,
    canViewFinancials: false,
    projectScope: 'assigned_only',
  },
  viewer: {
    projects: { view: true, create: false, edit: false, delete: false },
    employees: { view: true, create: false, edit: false, delete: false },
    finance: { view: false, create: false, edit: false, delete: false },
    tasks: { view: true, create: false, edit: false, delete: false },
    clients: { view: true, create: false, edit: false, delete: false },
    reports: { view: true, export: false },
    settings: { view: false, edit: false },
    canViewSalaries: false,
    canViewFinancials: false,
    projectScope: 'all',
  },
};

export function getInitialSeedData(): DatabaseSchema {
  return {
    settings: {
      name: 'Satora Lab',
      tagline: 'Enterprise Software & Digital Product Studio',
      logoUrl: '/logo.svg',
      currency: 'BDT',
      currencySymbol: '৳',
      timezone: 'Asia/Dhaka',
      address: 'Level 7, Concord Tower, Banani C/A, Dhaka-1213, Bangladesh',
      phone: '+880 1711-234567',
      email: 'operations@satoralab.com',
      taxId: 'BIN-00947219-0102',
      statuses: ['Planning', 'In Progress', 'Review', 'Completed', 'On Hold', 'Cancelled'],
      expenseCategories: [
        'Direct Project Cost',
        'Payroll',
        'Office Rent',
        'Software & Cloud Services',
        'Hardware & Equipment',
        'Utilities & Internet',
        'Travel & Client Meetings',
        'Marketing & Brand',
        'Legal & Professional Fees',
        'Miscellaneous Overhead',
      ],
      paymentMethods: [
        'Bank Transfer (BRAC Bank)',
        'Bank Transfer (City Bank)',
        'bKash Merchant',
        'Nagad Business',
        'Rocket',
        'Corporate Card',
        'Petty Cash',
      ],
      departments: ['Engineering', 'Design & UI/UX', 'Product Management', 'Quality Assurance', 'Operations', 'Finance & HR'],
    },
    users: [
      {
        id: 'USR-001',
        name: 'Asaduzzaman Rocky',
        email: 'asaduzzamanrocky@gmail.com',
        role: 'super_admin',
        employeeId: 'EMP-001',
        permissions: defaultPermissionsByRole.super_admin,
        avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
        createdAt: '2026-01-01T00:00:00.000Z',
      },
      {
        id: 'USR-002',
        name: 'Tasmia Rahman',
        email: 'tasmia@satoralab.com',
        role: 'management',
        employeeId: 'EMP-002',
        permissions: defaultPermissionsByRole.management,
        avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
        createdAt: '2026-01-05T00:00:00.000Z',
      },
      {
        id: 'USR-003',
        name: 'Kamrul Hasan',
        email: 'kamrul@satoralab.com',
        role: 'finance',
        employeeId: 'EMP-003',
        permissions: defaultPermissionsByRole.finance,
        avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
        createdAt: '2026-01-10T00:00:00.000Z',
      },
      {
        id: 'USR-004',
        name: 'Farhana Kabir',
        email: 'farhana@satoralab.com',
        role: 'hr',
        employeeId: 'EMP-004',
        permissions: defaultPermissionsByRole.hr,
        avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
        createdAt: '2026-01-12T00:00:00.000Z',
      },
      {
        id: 'USR-005',
        name: 'Zubair Ahmed',
        email: 'zubair@satoralab.com',
        role: 'project_manager',
        employeeId: 'EMP-005',
        permissions: defaultPermissionsByRole.project_manager,
        avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
        createdAt: '2026-01-15T00:00:00.000Z',
      },
      {
        id: 'USR-006',
        name: 'Nafis Fuad',
        email: 'nafis@satoralab.com',
        role: 'team_member',
        employeeId: 'EMP-006',
        permissions: defaultPermissionsByRole.team_member,
        avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
        createdAt: '2026-02-01T00:00:00.000Z',
      },
      {
        id: 'USR-007',
        name: 'Sabrina Sultana',
        email: 'sabrina@satoralab.com',
        role: 'viewer',
        employeeId: 'EMP-007',
        permissions: defaultPermissionsByRole.viewer,
        avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
        createdAt: '2026-02-15T00:00:00.000Z',
      },
    ],
    employees: [
      {
        id: 'EMP-001',
        name: 'Asaduzzaman Rocky',
        designation: 'Managing Director & Lead Architect',
        department: 'Operations',
        email: 'asaduzzamanrocky@gmail.com',
        phone: '+880 1711-234567',
        role: 'super_admin',
        joiningDate: '2024-01-01',
        salary: 185000,
        employmentStatus: 'Active',
      },
      {
        id: 'EMP-002',
        name: 'Tasmia Rahman',
        designation: 'Head of Operations & Strategy',
        department: 'Operations',
        email: 'tasmia@satoralab.com',
        phone: '+880 1712-345678',
        role: 'management',
        joiningDate: '2024-04-15',
        salary: 140000,
        employmentStatus: 'Active',
      },
      {
        id: 'EMP-003',
        name: 'Kamrul Hasan',
        designation: 'Senior Financial Controller',
        department: 'Finance & HR',
        email: 'kamrul@satoralab.com',
        phone: '+880 1713-456789',
        role: 'finance',
        joiningDate: '2024-06-01',
        salary: 115000,
        employmentStatus: 'Active',
      },
      {
        id: 'EMP-004',
        name: 'Farhana Kabir',
        designation: 'Lead People & Culture Partner',
        department: 'Finance & HR',
        email: 'farhana@satoralab.com',
        phone: '+880 1714-567890',
        role: 'hr',
        joiningDate: '2024-08-01',
        salary: 95000,
        employmentStatus: 'Active',
      },
      {
        id: 'EMP-005',
        name: 'Zubair Ahmed',
        designation: 'Principal Project Manager',
        department: 'Product Management',
        email: 'zubair@satoralab.com',
        phone: '+880 1715-678901',
        role: 'project_manager',
        joiningDate: '2024-09-10',
        salary: 125000,
        employmentStatus: 'Active',
      },
      {
        id: 'EMP-006',
        name: 'Nafis Fuad',
        designation: 'Senior Full Stack Engineer',
        department: 'Engineering',
        email: 'nafis@satoralab.com',
        phone: '+880 1716-789012',
        role: 'team_member',
        joiningDate: '2025-01-15',
        salary: 110000,
        employmentStatus: 'Active',
      },
      {
        id: 'EMP-007',
        name: 'Sabrina Sultana',
        designation: 'Senior UI/UX Product Designer',
        department: 'Design & UI/UX',
        email: 'sabrina@satoralab.com',
        phone: '+880 1717-890123',
        role: 'viewer',
        joiningDate: '2025-02-01',
        salary: 90000,
        employmentStatus: 'Active',
      },
      {
        id: 'EMP-008',
        name: 'Tanvir Hossain',
        designation: 'Cloud DevOps & Security Engineer',
        department: 'Engineering',
        email: 'tanvir@satoralab.com',
        phone: '+880 1718-901234',
        role: 'team_member',
        joiningDate: '2025-03-01',
        salary: 105000,
        employmentStatus: 'Active',
      },
      {
        id: 'EMP-009',
        name: 'Mehnaz Parveen',
        designation: 'QA Automation Lead',
        department: 'Quality Assurance',
        email: 'mehnaz@satoralab.com',
        phone: '+880 1719-012345',
        role: 'team_member',
        joiningDate: '2025-04-01',
        salary: 85000,
        employmentStatus: 'Active',
      },
    ],
    clients: [
      {
        id: 'CLI-101',
        company: 'bKash Limited',
        contactPerson: 'Muntasir Billah',
        email: 'muntasir.billah@bkash.com',
        phone: '+880 1711-998877',
        address: 'Shadhinata Bhaban, 8 Bir Uttam Mir Shawkat Sarak, Dhaka 1208',
        status: 'Active',
        followUpDate: '2026-10-18',
        notes: 'Enterprise account. Monthly review meetings scheduled for Q4 milestone releases.',
        createdAt: '2026-01-10T10:00:00.000Z',
      },
      {
        id: 'CLI-102',
        company: 'Aarong (BRAC Enterprises)',
        contactPerson: 'Sadia Chowdhury',
        email: 'sadia.c@aarong.brac.net',
        phone: '+880 1712-887766',
        address: 'Aarong Centre, 346 Tejgaon I/A, Dhaka-1208',
        status: 'Active',
        followUpDate: '2026-10-25',
        notes: 'Omnichannel inventory integration. Expanding mobile POS integration.',
        createdAt: '2026-01-20T11:00:00.000Z',
      },
      {
        id: 'CLI-103',
        company: 'Grameenphone Ltd',
        contactPerson: 'Rezwan Karim',
        email: 'rezwan.k@grameenphone.com',
        phone: '+880 1713-776655',
        address: 'GPHouse, Basundhara, Baridhara, Dhaka-1229',
        status: 'Active',
        followUpDate: '2026-10-12',
        notes: 'IoT telematics platform contract. Potential phase 2 rollout in December.',
        createdAt: '2026-02-05T09:30:00.000Z',
      },
      {
        id: 'CLI-104',
        company: 'Square Pharmaceuticals Ltd',
        contactPerson: 'Dr. Anisul Haque',
        email: 'anisul.h@squaregroup.com',
        phone: '+880 1714-665544',
        address: 'Square Centre, 48 Mohakhali C/A, Dhaka-1212',
        status: 'Active',
        followUpDate: '2026-10-15',
        notes: 'Cold-chain dispatch tracking & batch verification platform.',
        createdAt: '2026-02-15T14:00:00.000Z',
      },
      {
        id: 'CLI-105',
        company: 'Pathao Technologies',
        contactPerson: 'Shahriar Rifat',
        email: 'rifat.s@pathao.com',
        phone: '+880 1715-554433',
        address: 'Gulshan 2, Dhaka-1212',
        status: 'Lead',
        followUpDate: '2026-10-30',
        notes: 'Proposal submitted for logistics routing AI pilot.',
        createdAt: '2026-03-01T16:00:00.000Z',
      },
    ],
    projects: [
      {
        id: 'SL-PRJ-101',
        name: 'bKash Merchant Ecosystem Hub',
        clientId: 'CLI-101',
        managerId: 'EMP-005',
        assignedEmployeeIds: ['EMP-005', 'EMP-006', 'EMP-007', 'EMP-008'],
        startDate: '2026-06-01',
        deadline: '2026-11-30',
        status: 'In Progress',
        progress: 72,
        contractValue: 3500000,
        paymentsReceived: 2450000,
        directCosts: 520000,
        notes: 'Phase 1 deployed. Phase 2 merchant QR settlement testing in progress.',
        createdAt: '2026-05-20T10:00:00.000Z',
      },
      {
        id: 'SL-PRJ-102',
        name: 'Aarong Omnichannel Experience Platform',
        clientId: 'CLI-102',
        managerId: 'EMP-005',
        assignedEmployeeIds: ['EMP-005', 'EMP-006', 'EMP-007', 'EMP-009'],
        startDate: '2026-07-15',
        deadline: '2026-10-31',
        status: 'In Progress',
        progress: 85,
        contractValue: 2800000,
        paymentsReceived: 2100000,
        directCosts: 380000,
        notes: 'User acceptance testing ongoing. Go-live scheduled for end of month.',
        createdAt: '2026-07-01T09:00:00.000Z',
      },
      {
        id: 'SL-PRJ-103',
        name: 'Grameenphone IoT Fleet Telematics',
        clientId: 'CLI-103',
        managerId: 'EMP-001',
        assignedEmployeeIds: ['EMP-001', 'EMP-006', 'EMP-008'],
        startDate: '2026-05-01',
        deadline: '2026-09-30',
        status: 'Completed',
        progress: 100,
        contractValue: 4200000,
        paymentsReceived: 4200000,
        directCosts: 740000,
        notes: 'Final acceptance signoff received. Maintenance contract discussions in progress.',
        createdAt: '2026-04-15T08:30:00.000Z',
      },
      {
        id: 'SL-PRJ-104',
        name: 'Square Pharma Cold-Chain Dispatch',
        clientId: 'CLI-104',
        managerId: 'EMP-005',
        assignedEmployeeIds: ['EMP-005', 'EMP-008', 'EMP-009'],
        startDate: '2026-09-01',
        deadline: '2026-12-15',
        status: 'In Progress',
        progress: 35,
        contractValue: 3100000,
        paymentsReceived: 1200000,
        directCosts: 290000,
        notes: 'Sensor API integration completed. Dashboard analytics wireframes signed off.',
        createdAt: '2026-08-20T11:45:00.000Z',
      },
      {
        id: 'SL-PRJ-105',
        name: 'Pathao AI Routing Simulator (POC)',
        clientId: 'CLI-105',
        managerId: 'EMP-001',
        assignedEmployeeIds: ['EMP-001', 'EMP-006'],
        startDate: '2026-10-01',
        deadline: '2026-11-15',
        status: 'Planning',
        progress: 15,
        contractValue: 950000,
        paymentsReceived: 300000,
        directCosts: 45000,
        notes: 'Data ingestion pipeline setup and benchmark testing.',
        createdAt: '2026-09-28T15:20:00.000Z',
      },
      {
        id: 'SL-PRJ-106',
        name: 'Satora Internal Dev Tools & Mobile Portal',
        clientId: 'CLI-101', // Internal enterprise lab project
        managerId: 'EMP-005',
        assignedEmployeeIds: ['EMP-006', 'EMP-007', 'EMP-008', 'EMP-009'],
        startDate: '2026-08-01',
        deadline: '2026-10-20',
        status: 'Review',
        progress: 90,
        contractValue: 1200000,
        paymentsReceived: 1200000,
        directCosts: 180000,
        notes: 'PWA and offline sync features undergo final security audit.',
        createdAt: '2026-07-25T13:10:00.000Z',
      },
    ],
    tasks: [
      {
        id: 'TSK-101',
        projectId: 'SL-PRJ-101',
        title: 'Implement bKash Webhook Idempotency & Retries',
        description: 'Ensure double-charge prevention with Redis key locks and audit persistence.',
        assignedTo: ['EMP-006'],
        priority: 'Urgent',
        status: 'In Progress',
        progress: 80,
        startDate: '2026-09-25',
        dueDate: '2026-10-06',
        notes: 'Core logic written; stress-testing under simulated network drops.',
        createdAt: '2026-09-24T10:00:00.000Z',
      },
      {
        id: 'TSK-102',
        projectId: 'SL-PRJ-101',
        title: 'Merchant Analytics Settlement Export to Excel/CSV',
        description: 'Enable merchant admins to download reconciliation sheets formatted in BDT.',
        assignedTo: ['EMP-006', 'EMP-007'],
        priority: 'High',
        status: 'Done',
        progress: 100,
        startDate: '2026-09-18',
        dueDate: '2026-10-02',
        notes: 'Completed ahead of schedule.',
        createdAt: '2026-09-17T11:00:00.000Z',
      },
      {
        id: 'TSK-103',
        projectId: 'SL-PRJ-102',
        title: 'Aarong Mobile Cart Checkout Speed Optimization',
        description: 'Reduce mobile checkout payload size and optimize font/asset bundle.',
        assignedTo: ['EMP-006'],
        priority: 'High',
        status: 'In Progress',
        progress: 60,
        startDate: '2026-09-20',
        dueDate: '2026-10-03', // Overdue relative to current simulated date!
        notes: 'Blocked on staging CDN cache invalidation. Needs immediate escalation.',
        createdAt: '2026-09-19T09:00:00.000Z',
      },
      {
        id: 'TSK-104',
        projectId: 'SL-PRJ-102',
        title: 'Design System Dark Mode Tokens for Aarong POS',
        description: 'Standardize dark mode contrast ratios according to WCAG AAA standards.',
        assignedTo: ['EMP-007'],
        priority: 'Medium',
        status: 'Review',
        progress: 90,
        startDate: '2026-09-22',
        dueDate: '2026-10-08',
        notes: 'Figma specs linked and reviewed with Aarong design team.',
        createdAt: '2026-09-21T14:30:00.000Z',
      },
      {
        id: 'TSK-105',
        projectId: 'SL-PRJ-104',
        title: 'BLE Temperature Sensor Ingestion Daemon',
        description: 'Build Go/Node daemon to process 5-second interval temperature payloads.',
        assignedTo: ['EMP-008'],
        priority: 'Urgent',
        status: 'In Progress',
        progress: 45,
        startDate: '2026-09-28',
        dueDate: '2026-10-10',
        notes: 'Hardware sample kits received from Square Pharma logistics warehouse.',
        createdAt: '2026-09-27T10:15:00.000Z',
      },
      {
        id: 'TSK-106',
        projectId: 'SL-PRJ-104',
        title: 'Cold-Chain Alert SMS Gateway (Banglalink & GP)',
        description: 'Send instant SMS alerts to truck drivers whenever box temperature breaches 4°C.',
        assignedTo: ['EMP-008', 'EMP-009'],
        priority: 'High',
        status: 'To Do',
        progress: 0,
        startDate: '2026-10-05',
        dueDate: '2026-10-18',
        notes: 'Requires SMS API key provisioning from Square security team.',
        createdAt: '2026-09-28T16:00:00.000Z',
      },
      {
        id: 'TSK-107',
        projectId: 'SL-PRJ-105',
        title: 'Pathao Graph Hopper Multi-Stop Route Simulation',
        description: 'Simulate delivery route optimization for 100 concurrent parcel dispatches in Dhanmondi.',
        assignedTo: ['EMP-006'],
        priority: 'Medium',
        status: 'In Progress',
        progress: 30,
        startDate: '2026-10-01',
        dueDate: '2026-10-14',
        notes: 'Initial test dataset processed.',
        createdAt: '2026-09-30T12:00:00.000Z',
      },
      {
        id: 'TSK-108',
        projectId: 'SL-PRJ-106',
        title: 'PWA Background Sync & Service Worker Offline Storage',
        description: 'Allow managers and developers to view project metrics and queue offline edits on Android.',
        assignedTo: ['EMP-006', 'EMP-007'],
        priority: 'Urgent',
        status: 'Review',
        progress: 95,
        startDate: '2026-09-15',
        dueDate: '2026-10-05',
        notes: 'Fully functional, testing edge case reconnects.',
        createdAt: '2026-09-14T09:30:00.000Z',
      },
      {
        id: 'TSK-109',
        projectId: 'SL-PRJ-102',
        title: 'End-to-End Cypress Smoke Test Suite for Aarong Checkout',
        description: 'Automated test suite across Chrome, Safari, and Firefox.',
        assignedTo: ['EMP-009'],
        priority: 'High',
        status: 'In Progress',
        progress: 75,
        startDate: '2026-09-26',
        dueDate: '2026-10-07',
        notes: '18 of 24 critical user journeys covered.',
        createdAt: '2026-09-25T15:00:00.000Z',
      },
      {
        id: 'TSK-110',
        projectId: 'SL-PRJ-103',
        title: 'GP Telematics Final Security Penetration Report Remediation',
        description: 'Verify TLS 1.3 enforcement and token revocation endpoints.',
        assignedTo: ['EMP-008'],
        priority: 'Medium',
        status: 'Done',
        progress: 100,
        startDate: '2026-09-10',
        dueDate: '2026-09-25',
        notes: 'Signed off by GP Infosec team.',
        createdAt: '2026-09-08T10:00:00.000Z',
      },
    ],
    transactions: [
      // September & October 2026 financial records
      {
        id: 'TRX-2026-001',
        type: 'income',
        date: '2026-09-05',
        projectId: 'SL-PRJ-101',
        isCompanyOverhead: false,
        category: 'Client Payment',
        description: 'Milestone 2 payment received for bKash Merchant Portal',
        amount: 1050000,
        paymentMethod: 'Bank Transfer (BRAC Bank)',
        reference: 'BRAC-TX-8492019',
        paymentStatus: 'Received',
        invoiceNumber: 'INV-2026-081',
        clientName: 'bKash Limited',
        createdAt: '2026-09-05T14:30:00.000Z',
      },
      {
        id: 'TRX-2026-002',
        type: 'income',
        date: '2026-09-12',
        projectId: 'SL-PRJ-102',
        isCompanyOverhead: false,
        category: 'Client Payment',
        description: 'Milestone 3: Mobile checkout integration delivery',
        amount: 800000,
        paymentMethod: 'Bank Transfer (City Bank)',
        reference: 'CTY-DEP-992144',
        paymentStatus: 'Received',
        invoiceNumber: 'INV-2026-083',
        clientName: 'Aarong (BRAC Enterprises)',
        createdAt: '2026-09-12T16:00:00.000Z',
      },
      {
        id: 'TRX-2026-003',
        type: 'income',
        date: '2026-09-20',
        projectId: 'SL-PRJ-103',
        isCompanyOverhead: false,
        category: 'Client Payment',
        description: 'Final payment received for GP IoT Telematics platform',
        amount: 1400000,
        paymentMethod: 'Bank Transfer (BRAC Bank)',
        reference: 'GP-SETTLE-88129',
        paymentStatus: 'Received',
        invoiceNumber: 'INV-2026-085',
        clientName: 'Grameenphone Ltd',
        createdAt: '2026-09-20T11:20:00.000Z',
      },
      {
        id: 'TRX-2026-004',
        type: 'income',
        date: '2026-10-02',
        projectId: 'SL-PRJ-104',
        isCompanyOverhead: false,
        category: 'Client Payment',
        description: 'Mobilization advance (40%) for Square Pharma Cold-Chain',
        amount: 1200000,
        paymentMethod: 'Bank Transfer (City Bank)',
        reference: 'SQR-ADV-44102',
        paymentStatus: 'Received',
        invoiceNumber: 'INV-2026-091',
        clientName: 'Square Pharmaceuticals Ltd',
        createdAt: '2026-10-02T13:00:00.000Z',
      },
      {
        id: 'TRX-2026-005',
        type: 'income',
        date: '2026-10-03',
        projectId: 'SL-PRJ-105',
        isCompanyOverhead: false,
        category: 'Client Payment',
        description: 'POC kickoff fee received for Pathao AI Routing Simulator',
        amount: 300000,
        paymentMethod: 'bKash Merchant',
        reference: 'BKASH-MCH-992381',
        paymentStatus: 'Received',
        invoiceNumber: 'INV-2026-092',
        clientName: 'Pathao Technologies',
        createdAt: '2026-10-03T17:15:00.000Z',
      },
      // Expenses: Single-entry payroll for September (recorded once)
      {
        id: 'TRX-2026-006',
        type: 'expense',
        date: '2026-09-30',
        projectId: null,
        isCompanyOverhead: true,
        category: 'Payroll',
        description: 'Total September 2026 Staff Payroll disbursement (9 full-time employees)',
        amount: 950000,
        paymentMethod: 'Bank Transfer (BRAC Bank)',
        reference: 'SALARY-DISB-SEP26',
        paymentStatus: 'Paid',
        createdAt: '2026-09-30T10:00:00.000Z',
      },
      // Company Overheads
      {
        id: 'TRX-2026-007',
        type: 'expense',
        date: '2026-09-01',
        projectId: null,
        isCompanyOverhead: true,
        category: 'Office Rent',
        description: 'Banani Concord Tower Office Rent for September 2026',
        amount: 220000,
        paymentMethod: 'Bank Transfer (BRAC Bank)',
        reference: 'RENT-BANANI-SEP26',
        paymentStatus: 'Paid',
        createdAt: '2026-09-01T09:00:00.000Z',
      },
      {
        id: 'TRX-2026-008',
        type: 'expense',
        date: '2026-09-10',
        projectId: null,
        isCompanyOverhead: true,
        category: 'Software & Cloud Services',
        description: 'AWS Cloud & GitHub Enterprise Monthly Billing',
        amount: 145000,
        paymentMethod: 'Corporate Card',
        reference: 'AWS-INV-77491',
        paymentStatus: 'Paid',
        createdAt: '2026-09-10T12:00:00.000Z',
      },
      {
        id: 'TRX-2026-009',
        type: 'expense',
        date: '2026-09-15',
        projectId: null,
        isCompanyOverhead: true,
        category: 'Utilities & Internet',
        description: 'Dedicated Fiber Internet (Link3) + DESCO Electricity',
        amount: 48000,
        paymentMethod: 'bKash Merchant',
        reference: 'UTIL-SEP-3391',
        paymentStatus: 'Paid',
        createdAt: '2026-09-15T15:30:00.000Z',
      },
      // Direct Project Expenses
      {
        id: 'TRX-2026-010',
        type: 'expense',
        date: '2026-09-18',
        projectId: 'SL-PRJ-101',
        isCompanyOverhead: false,
        category: 'Direct Project Cost',
        description: 'Dedicated staging load balancer & isolated VPC for bKash',
        amount: 95000,
        paymentMethod: 'Corporate Card',
        reference: 'DIR-BKASH-VPC',
        paymentStatus: 'Paid',
        createdAt: '2026-09-18T14:15:00.000Z',
      },
      {
        id: 'TRX-2026-011',
        type: 'expense',
        date: '2026-09-22',
        projectId: 'SL-PRJ-102',
        isCompanyOverhead: false,
        category: 'Direct Project Cost',
        description: 'Fastly CDN Edge Compute license for Aarong High-Concurrency Checkout',
        amount: 110000,
        paymentMethod: 'Corporate Card',
        reference: 'DIR-AARONG-FASTLY',
        paymentStatus: 'Paid',
        createdAt: '2026-09-22T16:45:00.000Z',
      },
      {
        id: 'TRX-2026-012',
        type: 'expense',
        date: '2026-10-01',
        projectId: null,
        isCompanyOverhead: true,
        category: 'Office Rent',
        description: 'Banani Concord Tower Office Rent for October 2026',
        amount: 220000,
        paymentMethod: 'Bank Transfer (BRAC Bank)',
        reference: 'RENT-BANANI-OCT26',
        paymentStatus: 'Paid',
        createdAt: '2026-10-01T09:00:00.000Z',
      },
      {
        id: 'TRX-2026-013',
        type: 'expense',
        date: '2026-10-02',
        projectId: 'SL-PRJ-104',
        isCompanyOverhead: false,
        category: 'Direct Project Cost',
        description: 'Bluetooth IoT sensor dev kits & calibrated thermal probes',
        amount: 85000,
        paymentMethod: 'Bank Transfer (City Bank)',
        reference: 'DIR-SQR-SENSORS',
        paymentStatus: 'Paid',
        createdAt: '2026-10-02T16:00:00.000Z',
      },
    ],
    invoices: [
      {
        id: 'INV-2026-091',
        projectId: 'SL-PRJ-104',
        clientId: 'CLI-104',
        invoiceNumber: 'INV-2026-091',
        issueDate: '2026-09-28',
        dueDate: '2026-10-12',
        items: [
          {
            description: 'Phase 1 Architecture, Sensor Specs & Project Mobilization',
            quantity: 1,
            unitPrice: 1200000,
            total: 1200000,
          },
        ],
        totalAmount: 1200000,
        paidAmount: 1200000,
        status: 'Paid',
        notes: 'Payment confirmed via City Bank on Oct 2, 2026.',
      },
      {
        id: 'INV-2026-092',
        projectId: 'SL-PRJ-105',
        clientId: 'CLI-105',
        invoiceNumber: 'INV-2026-092',
        issueDate: '2026-10-01',
        dueDate: '2026-10-15',
        items: [
          {
            description: 'Algorithm POC Research & Data Ingestion Setup',
            quantity: 1,
            unitPrice: 300000,
            total: 300000,
          },
        ],
        totalAmount: 300000,
        paidAmount: 300000,
        status: 'Paid',
        notes: 'Settled via bKash Merchant account.',
      },
      {
        id: 'INV-2026-093',
        projectId: 'SL-PRJ-101',
        clientId: 'CLI-101',
        invoiceNumber: 'INV-2026-093',
        issueDate: '2026-10-03',
        dueDate: '2026-10-25',
        items: [
          {
            description: 'Phase 2: Merchant Settlement Engine & QR Code APIs',
            quantity: 1,
            unitPrice: 1050000,
            total: 1050000,
          },
        ],
        totalAmount: 1050000,
        paidAmount: 0,
        status: 'Sent',
        notes: 'Pending bKash internal voucher approval.',
      },
      {
        id: 'INV-2026-094',
        projectId: 'SL-PRJ-102',
        clientId: 'CLI-102',
        invoiceNumber: 'INV-2026-094',
        issueDate: '2026-10-04',
        dueDate: '2026-10-20',
        items: [
          {
            description: 'UAT Signoff Milestone: Omnichannel Inventory Sync',
            quantity: 1,
            unitPrice: 700000,
            total: 700000,
          },
        ],
        totalAmount: 700000,
        paidAmount: 0,
        status: 'Sent',
        notes: 'Final settlement invoice upon signoff.',
      },
    ],
    auditLogs: [
      {
        id: 'AUD-001',
        timestamp: '2026-10-01T09:05:00.000Z',
        userId: 'USR-001',
        userName: 'Asaduzzaman Rocky',
        userRole: 'super_admin',
        action: 'LOGIN',
        resource: 'Auth',
        details: 'Admin session initiated from Banani Office workstation (103.114.96.2).',
      },
      {
        id: 'AUD-002',
        timestamp: '2026-10-02T13:05:00.000Z',
        userId: 'USR-003',
        userName: 'Kamrul Hasan',
        userRole: 'finance',
        action: 'CREATE',
        resource: 'Transactions',
        details: 'Recorded advance payment ৳1,200,000 for Square Pharma (INV-2026-091).',
      },
      {
        id: 'AUD-003',
        timestamp: '2026-10-03T11:30:00.000Z',
        userId: 'USR-005',
        userName: 'Zubair Ahmed',
        userRole: 'project_manager',
        action: 'UPDATE',
        resource: 'Projects',
        details: 'Updated progress of SL-PRJ-101 (bKash) to 72%. Milestone 2 approved.',
      },
      {
        id: 'AUD-004',
        timestamp: '2026-10-04T08:15:00.000Z',
        userId: 'USR-001',
        userName: 'Asaduzzaman Rocky',
        userRole: 'super_admin',
        action: 'ROLE_CHANGE',
        resource: 'Users',
        details: 'Verified role access policies and enabled Dhaka timezone BDT financial auditing.',
      },
    ],
    paymentOptions: [
      {
        id: 'PAY-001',
        title: 'BRAC Bank Corporate Current A/C',
        type: 'bank',
        accountName: 'Satora Lab Limited',
        accountNumber: '15012048912001',
        routingNumber: '060271638',
        branch: 'Banani Branch, Dhaka',
        instructions: 'Please include your Invoice or Project ID (e.g. SL-PRJ-101) in the transaction remark.',
        isActive: true,
        createdBy: 'USR-001',
        createdAt: '2026-01-01T00:00:00.000Z',
      },
      {
        id: 'PAY-002',
        title: 'City Bank High-Value Operations A/C',
        type: 'bank',
        accountName: 'Satora Lab Limited',
        accountNumber: '3102498214001',
        routingNumber: '225272314',
        branch: 'Gulshan 2 Branch, Dhaka',
        instructions: 'Preferred for client RTGS/BEFTN transfers over BDT 5,00,000.',
        isActive: true,
        createdBy: 'USR-001',
        createdAt: '2026-01-01T00:00:00.000Z',
      },
      {
        id: 'PAY-003',
        title: 'bKash Merchant Pay Account',
        type: 'mfs',
        accountName: 'Satora Lab Tech Hub',
        accountNumber: '01711-234567',
        instructions: 'Select "Make Payment" from bKash App or dial *247#. Counter: 01.',
        isActive: true,
        createdBy: 'USR-001',
        createdAt: '2026-01-05T00:00:00.000Z',
      },
      {
        id: 'PAY-004',
        title: 'Nagad Business Gateway',
        type: 'mfs',
        accountName: 'Satora Lab Enterprise',
        accountNumber: '01819-887766',
        instructions: 'Dial *167# or use Nagad App -> Merchant Payment. Reference: Project ID.',
        isActive: true,
        createdBy: 'USR-001',
        createdAt: '2026-01-05T00:00:00.000Z',
      },
      {
        id: 'PAY-005',
        title: 'Dutch Bangla Bank Rocket',
        type: 'mfs',
        accountName: 'Satora Lab Limited',
        accountNumber: '01912-334455-9',
        instructions: 'Merchant pay via Rocket menu. Enter reference as Invoice number.',
        isActive: true,
        createdBy: 'USR-001',
        createdAt: '2026-01-10T00:00:00.000Z',
      },
      {
        id: 'PAY-006',
        title: 'HQ Office Petty Cash Vault',
        type: 'cash',
        accountName: 'Satora Lab Operations Banani',
        accountNumber: 'VAULT-DHAKA-L7',
        instructions: 'Direct cash deposit at Level 7 Concord Tower Banani. Official voucher signed by accountant.',
        isActive: true,
        createdBy: 'USR-001',
        createdAt: '2026-01-15T00:00:00.000Z',
      },
    ],
    chatChannels: [
      {
        id: 'CHN-001',
        name: 'general',
        type: 'public_channel',
        members: ['*'],
        description: 'Company-wide announcements and team discussions for Satora Lab.',
        createdBy: 'USR-001',
        createdAt: '2026-01-01T00:00:00.000Z',
      },
      {
        id: 'CHN-002',
        name: 'engineering',
        type: 'public_channel',
        members: ['*'],
        description: 'Architecture discussions, PR reviews, CI/CD deploys, and technical sync.',
        createdBy: 'USR-001',
        createdAt: '2026-01-01T00:00:00.000Z',
      },
      {
        id: 'CHN-003',
        name: 'finance-and-ops',
        type: 'public_channel',
        members: ['USR-001', 'USR-002', 'USR-003', 'USR-004'],
        description: 'Voucher settlements, invoice releases, and bank reconciliation in BDT.',
        createdBy: 'USR-003',
        createdAt: '2026-01-05T00:00:00.000Z',
      },
      {
        id: 'CHN-PRJ-101',
        name: 'Project: bKash Merchant Hub',
        type: 'project',
        projectId: 'SL-PRJ-101',
        members: ['USR-001', 'USR-005', 'USR-006', 'USR-007'],
        description: 'Dedicated room for bKash Merchant Ecosystem Hub deliverables.',
        createdBy: 'USR-005',
        createdAt: '2026-06-01T00:00:00.000Z',
      },
      {
        id: 'CHN-PRJ-102',
        name: 'Project: Aarong Experience',
        type: 'project',
        projectId: 'SL-PRJ-102',
        members: ['USR-001', 'USR-005', 'USR-006', 'USR-007'],
        description: 'Omnichannel inventory integration and high-speed checkout sprint room.',
        createdBy: 'USR-005',
        createdAt: '2026-07-15T00:00:00.000Z',
      },
      {
        id: 'CHN-PRJ-104',
        name: 'Project: Square Pharma Cold-Chain',
        type: 'project',
        projectId: 'SL-PRJ-104',
        members: ['USR-001', 'USR-005', 'USR-006'],
        description: 'BLE temperature sensor data processing and logistics alerts.',
        createdBy: 'USR-005',
        createdAt: '2026-09-01T00:00:00.000Z',
      },
      {
        id: 'CHN-DM-001',
        name: 'Direct: Asaduzzaman & Kamrul',
        type: 'direct',
        members: ['USR-001', 'USR-003'],
        description: 'Direct thread between Lead Architect and Financial Controller.',
        createdBy: 'USR-001',
        createdAt: '2026-09-20T00:00:00.000Z',
      },
    ],
    chatMessages: [
      {
        id: 'MSG-001',
        channelId: 'CHN-001',
        senderId: 'USR-001',
        senderName: 'Asaduzzaman Rocky',
        senderRole: 'super_admin',
        text: 'Welcome team to the updated Satora Lab workspace! All project timelines, BDT financials, and credentials vault are synchronized.',
        createdAt: '2026-10-01T09:00:00.000Z',
      },
      {
        id: 'MSG-002',
        channelId: 'CHN-001',
        senderId: 'USR-002',
        senderName: 'Tasmia Rahman',
        senderRole: 'management',
        text: 'Great work on closing Q3 deliverables! bKash Phase 2 testing is on track for this month.',
        createdAt: '2026-10-01T09:15:00.000Z',
      },
      {
        id: 'MSG-003',
        channelId: 'CHN-PRJ-101',
        senderId: 'USR-005',
        senderName: 'Zubair Ahmed',
        senderRole: 'project_manager',
        text: 'Nafis, how is the webhook idempotency testing going under high concurrency?',
        createdAt: '2026-10-02T11:00:00.000Z',
      },
      {
        id: 'MSG-004',
        channelId: 'CHN-PRJ-101',
        senderId: 'USR-006',
        senderName: 'Nafis Fuad',
        senderRole: 'team_member',
        text: 'Redis lock prevents duplicate transaction events. Re-tested with 5,000 simulated merchant QR settlements and 0 collision occurred.',
        createdAt: '2026-10-02T11:25:00.000Z',
      },
      {
        id: 'MSG-005',
        channelId: 'CHN-003',
        senderId: 'USR-003',
        senderName: 'Kamrul Hasan',
        senderRole: 'finance',
        text: 'Square Pharma 40% mobilization advance (৳1,200,000) has cleared via City Bank. Invoice INV-2026-091 marked Paid.',
        createdAt: '2026-10-02T14:00:00.000Z',
      },
      {
        id: 'MSG-006',
        channelId: 'CHN-DM-001',
        senderId: 'USR-003',
        senderName: 'Kamrul Hasan',
        senderRole: 'finance',
        text: 'Rocky bhai, September payroll of ৳950,000 has been completely reconciled with BRAC Bank corporate statement.',
        createdAt: '2026-10-03T10:00:00.000Z',
      },
      {
        id: 'MSG-007',
        channelId: 'CHN-DM-001',
        senderId: 'USR-001',
        senderName: 'Asaduzzaman Rocky',
        senderRole: 'super_admin',
        text: 'Excellent Kamrul! Please ensure the upcoming Fastly CDN license for Aarong checkout is logged as a direct project expense.',
        createdAt: '2026-10-03T10:15:00.000Z',
      },
    ],
    messageRequests: [
      {
        id: 'REQ-001',
        requesterId: 'USR-006',
        requesterName: 'Nafis Fuad',
        requesterEmail: 'nafis@satoralab.com',
        targetUserId: 'USR-001',
        subject: 'Cloudflare CDN Token for Aarong Mobile Optimization',
        message: 'Hello Rocky bhai, we need staging API tokens for the Aarong edge compute bundle test.',
        status: 'pending',
        createdAt: '2026-10-03T16:00:00.000Z',
      },
      {
        id: 'REQ-002',
        requesterId: 'USR-007',
        requesterName: 'Sabrina Sultana',
        requesterEmail: 'sabrina@satoralab.com',
        targetUserId: 'USR-002',
        subject: 'Figma Design System Tokens Export Review',
        message: 'Tasmia apu, please review the latest WCAG contrast tokens before the client walkthrough.',
        status: 'accepted',
        createdAt: '2026-10-02T15:30:00.000Z',
      },
    ],
    vaultCredentials: [
      {
        id: 'VLT-001',
        title: 'ChatGPT Plus Team Workspace (OpenAI)',
        category: 'AI Tools',
        serviceUrl: 'https://chatgpt.com',
        username: 'ai-core@satoralab.com',
        password: 'Satora$AI#gpt2026!Key',
        recoveryNotes: 'Assigned for Engineering & Tech Lead research. 2FA managed via Google Authenticator.',
        accessScope: 'restricted',
        assignedUserIds: ['USR-001', 'USR-005', 'USR-006'], // Rocky, Zubair, Nafis
        createdBy: 'USR-001',
        createdAt: '2026-09-01T00:00:00.000Z',
        updatedAt: '2026-09-15T00:00:00.000Z',
      },
      {
        id: 'VLT-002',
        title: 'AWS Production Cloud Console',
        category: 'Cloud & Hosting',
        serviceUrl: 'https://signin.aws.amazon.com/console',
        username: 'root@satoralab.com',
        password: 'AWS#DhakaProd@2026%Secure',
        recoveryNotes: 'Strict YubiKey hardware token enforcement required. Do not share outside devops.',
        accessScope: 'restricted',
        assignedUserIds: ['USR-001', 'USR-006'], // Rocky and Nafis
        createdBy: 'USR-001',
        createdAt: '2026-08-15T00:00:00.000Z',
        updatedAt: '2026-09-20T00:00:00.000Z',
      },
      {
        id: 'VLT-003',
        title: 'GitHub Enterprise Organization',
        category: 'Development & Git',
        serviceUrl: 'https://github.com/satora-lab',
        username: 'admin@satoralab.com',
        password: 'Gh$Enterprise#2026Satora',
        recoveryNotes: 'SSH keys must be linked to verified @satoralab.com domain emails.',
        accessScope: 'restricted',
        assignedUserIds: ['USR-001', 'USR-005', 'USR-006', 'USR-007'],
        createdBy: 'USR-001',
        createdAt: '2026-07-01T00:00:00.000Z',
        updatedAt: '2026-09-10T00:00:00.000Z',
      },
      {
        id: 'VLT-004',
        title: 'bKash Merchant Production API Portal',
        category: 'Banking & Gateway',
        serviceUrl: 'https://merchant.bkash.com/portal',
        username: 'merch-884920',
        password: 'bKash$API#Live9910!',
        recoveryNotes: 'IP Whitelisted to Banani Office static IP (103.114.96.2).',
        accessScope: 'restricted',
        assignedUserIds: ['USR-001', 'USR-003', 'USR-005'], // Rocky, Kamrul (Finance), Zubair (PM)
        createdBy: 'USR-001',
        createdAt: '2026-06-10T00:00:00.000Z',
        updatedAt: '2026-09-25T00:00:00.000Z',
      },
      {
        id: 'VLT-005',
        title: 'Figma Enterprise Design Team',
        category: 'Design & Media',
        serviceUrl: 'https://www.figma.com',
        username: 'design@satoralab.com',
        password: 'Figma$Design@Satora26',
        recoveryNotes: 'Design library tokens synced with Tailwind build system.',
        accessScope: 'all',
        assignedUserIds: ['USR-001', 'USR-002', 'USR-005', 'USR-006', 'USR-007'],
        createdBy: 'USR-001',
        createdAt: '2026-05-20T00:00:00.000Z',
        updatedAt: '2026-08-30T00:00:00.000Z',
      },
    ],
  };
}

class DatabaseManager {
  private data: DatabaseSchema | null = null;

  constructor() {
    this.ensureDirectoryAndInit();
  }

  private ensureDirectoryAndInit() {
    if (!fs.existsSync(DATA_DIR)) {
      fs.mkdirSync(DATA_DIR, { recursive: true });
    }

    if (!fs.existsSync(DB_FILE)) {
      const initial = getInitialSeedData();
      fs.writeFileSync(DB_FILE, JSON.stringify(initial, null, 2), 'utf-8');
      this.data = initial;
    } else {
      try {
        const raw = fs.readFileSync(DB_FILE, 'utf-8');
        this.data = JSON.parse(raw);
        // Ensure new schema arrays are initialized if missing from prior file
        const defaults = getInitialSeedData();
        let needsSave = false;
        if (this.data) {
          if (!this.data.paymentOptions || this.data.paymentOptions.length === 0) {
            this.data.paymentOptions = defaults.paymentOptions;
            needsSave = true;
          }
          if (!this.data.chatChannels || this.data.chatChannels.length === 0) {
            this.data.chatChannels = defaults.chatChannels;
            needsSave = true;
          }
          if (!this.data.chatMessages || this.data.chatMessages.length === 0) {
            this.data.chatMessages = defaults.chatMessages;
            needsSave = true;
          }
          if (!this.data.messageRequests) {
            this.data.messageRequests = defaults.messageRequests;
            needsSave = true;
          }
          if (!this.data.vaultCredentials || this.data.vaultCredentials.length === 0) {
            this.data.vaultCredentials = defaults.vaultCredentials;
            needsSave = true;
          }
          if (needsSave) {
            fs.writeFileSync(DB_FILE, JSON.stringify(this.data, null, 2), 'utf-8');
          }
        }
      } catch (err) {
        console.error('Error reading database, creating fresh backup and seed:', err);
        const initial = getInitialSeedData();
        fs.writeFileSync(DB_FILE, JSON.stringify(initial, null, 2), 'utf-8');
        this.data = initial;
      }
    }
  }

  public get(): DatabaseSchema {
    if (!this.data) {
      this.ensureDirectoryAndInit();
    }
    return this.data!;
  }

  public save(data: DatabaseSchema): void {
    this.data = data;
    try {
      const tempFile = `${DB_FILE}.tmp`;
      fs.writeFileSync(tempFile, JSON.stringify(data, null, 2), 'utf-8');
      fs.renameSync(tempFile, DB_FILE);
    } catch (e) {
      console.error('Failed to atomic write db file:', e);
      fs.writeFileSync(DB_FILE, JSON.stringify(data, null, 2), 'utf-8');
    }
  }

  public logAudit(log: Omit<DatabaseSchema['auditLogs'][0], 'id' | 'timestamp'>): void {
    const db = this.get();
    const newLog = {
      id: `AUD-${Date.now().toString(36).toUpperCase()}-${Math.floor(Math.random() * 1000)}`,
      timestamp: new Date().toISOString(),
      ...log,
    };
    db.auditLogs.unshift(newLog);
    // keep last 500 audit logs
    if (db.auditLogs.length > 500) {
      db.auditLogs = db.auditLogs.slice(0, 500);
    }
    this.save(db);
  }

  public resetToDefaults(): DatabaseSchema {
    const initial = getInitialSeedData();
    this.save(initial);
    return initial;
  }
}

export const dbManager = new DatabaseManager();
